### ISSUE TITLE
Install with php8

### ISSUE THREAD

**Issue by eydun** [dakujem/selectoo#5]
When I try to install with `composer require dakujem/selectoo:2.01` I get the error:

`- dakujem/selectoo v2.0.1 requires php ^7.1 -> your php version (8.2.0) does not satisfy that requirement.`

Is it not supposed to work with php8?

Thanks!

**Comment by dakujem** [comment]
Hi, Eydun. It should be possible now. Just use
```
composer req "dakujem/selectoo:^2.1"
```
Should you encounter issues, let me know. I'm not really using this package anymore.
